### ISSUE TITLE
ImportError: No module named 'urllib2' with Python3

### ISSUE THREAD

**Issue by hostingnuggets** [toddrob99/pyprowl#7]
I can't seem to make your library work with Python 3 as it is looking for urllib2 which is for Python 2 as you can see from the output below:

```
  File "/usr/local/lib/python3.5/dist-packages/pyprowl/__init__.py", line 76, in notify
    return self.api_call('add',data)
  File "/usr/local/lib/python3.5/dist-packages/pyprowl/__init__.py", line 91, in api_call
    import urllib2, urllib
ImportError: No module named 'urllib2'
```
Would it be possible to make your code compatible also with Python 3?

Thank you very much in advance.

**Comment by toddrob99** [comment]
Python 3 support is on my to-do list, since Python 2.7 end of life is coming up.

**Comment by hostingnuggets** [comment]
Fantastic! If there is any quick and dirty patch to swap urllib2 with urllib3 let me know, I will try it out directly in pyprowl's `__init__.py` file.

**Comment by toddrob99** [comment]
I actually just published a new version that includes python 3 support, so you can simply update to v3.0.0 from pip.

**Comment by hostingnuggets** [comment]
Wow that was fast, thank you very much it works nicely :+1:
