### ISSUE TITLE
Pass variable to pyprowl

### ISSUE THREAD

**Issue by pbertain** [toddrob99/pyprowl#8]
This might not be the proper method but I like what I get so far from pyprowl but cannot pass a variable to any of the sections in notify.

I'd like to have each "event" contain a variable with the thing I am watching for.  I am running this in a for loop and want to send a Prowl notification when I see the item I am watching for but it errors out.  I feel like it might be possible but I just can't figure it out!

**Comment by toddrob99** [comment]
You can include a variable in the event and/or description parameters of the notify method. They are just strings, so you can use str.format(), f-strings, or string concatenation to include a variable. The example from the readme is below, with variables added to the event and description.

I added/modified the following lines:
`myVar = 'test'`  # Define the variable to include
`p.notify(event='Event name; variable: {}'.format(myVar), description='Description of event; variable: {}'.format(myVar),`  # Include the variable

```
import pyprowl

p = pyprowl.Prowl('YOUR_PROWL_API_KEY')

try:
	p.verify_key()
	print("Prowl API key successfully verified!")
except Exception as e:
	print("Error verifying Prowl API key: {}".format(e))
	exit()

myVar = 'test'
try:
	p.notify(event='Event name; variable: {}'.format(myVar), description='Description of event; variable: {}'.format(myVar), 
			 priority=0, url='http://www.example.com', 
			 #apiKey='uncomment and add API KEY here if different', 
			 appName='Name of app sending the notification')
	print("Notification successfully sent to Prowl!")
except Exception as e:
	print("Error sending notification to Prowl: {}".format(e))
```

**Comment by pbertain** [comment]
Oh man!  So cool.. and sadly, so easy! ;) Thanks for the help / updates.  PyProwl is working like a charm!
